//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistryExplorer.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RegistryExplorer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure you want to delete selected entries? ähnelt.
        /// </summary>
        internal static string Confirm_DeleteEntries {
            get {
                return ResourceManager.GetString("Confirm_DeleteEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure you want to delete this key and all of its subkeys? ähnelt.
        /// </summary>
        internal static string Confirm_DeleteKey {
            get {
                return ResourceManager.GetString("Confirm_DeleteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure you want to delete these values? ähnelt.
        /// </summary>
        internal static string Confirm_DeleteValue {
            get {
                return ResourceManager.GetString("Confirm_DeleteValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is already a favorite with that name. ähnelt.
        /// </summary>
        internal static string Error_AlreadyFavorite {
            get {
                return ResourceManager.GetString("Error_AlreadyFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot create key: Error writing to the registry. ähnelt.
        /// </summary>
        internal static string Error_CreateKeyFail {
            get {
                return ResourceManager.GetString("Error_CreateKeyFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot create value: Error writing to the registry. ähnelt.
        /// </summary>
        internal static string Error_CreateValueFail {
            get {
                return ResourceManager.GetString("Error_CreateValueFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Some entries could not be deleted. ähnelt.
        /// </summary>
        internal static string Error_DeleteEntriesFail {
            get {
                return ResourceManager.GetString("Error_DeleteEntriesFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not delete the specified key. ähnelt.
        /// </summary>
        internal static string Error_DeleteKeyFail {
            get {
                return ResourceManager.GetString("Error_DeleteKeyFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Some values could not be deleted. ähnelt.
        /// </summary>
        internal static string Error_DeleteValueFail {
            get {
                return ResourceManager.GetString("Error_DeleteValueFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was an error exporting the file. ähnelt.
        /// </summary>
        internal static string Error_ExportFail {
            get {
                return ResourceManager.GetString("Error_ExportFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to open the file. ähnelt.
        /// </summary>
        internal static string Error_FileOpenFail {
            get {
                return ResourceManager.GetString("Error_FileOpenFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid registry key specified. ähnelt.
        /// </summary>
        internal static string Error_InvalidKey {
            get {
                return ResourceManager.GetString("Error_InvalidKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export complete. ähnelt.
        /// </summary>
        internal static string Info_ExportSuccess {
            get {
                return ResourceManager.GetString("Info_ExportSuccess", resourceCulture);
            }
        }
    }
}
